// Non functional android library used to provide Android Studio editor support to the project.
plugins {
    id 'com.android.library'
}

android {
    compileSdk = versions.compileSdk
    buildToolsVersion = versions.buildTools
    ndkVersion versions.ndkVersion

    namespace = "org.godotengine.godot.nativesrcs"

    defaultConfig {
        minSdk = versions.minSdk
        targetSdk = versions.targetSdk
    }

    compileOptions {
        sourceCompatibility versions.javaVersion
        targetCompatibility versions.javaVersion
    }

    packaging {
        resources {
            excludes += ['META-INF/LICENSE', 'META-INF/NOTICE']
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

dependencies {}

androidComponents {
    onVariants(selector().all()) { variant ->
        def buildType = variant.buildType.capitalize()

        def taskPrefix = ""
        if (project.path != ":") {
            taskPrefix = project.path + ":"
        }

        // Disable the externalNativeBuild* task as it would cause build failures since the cmake build
        // files is only setup for editing support.
        gradle.startParameter.excludedTaskNames += taskPrefix + "externalNativeBuild" + buildType
    }
}
